http:
  routers:
    web:
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      service: s-active
    test:
      entryPoints:
        - web2
      rule: "PathPrefix(`/`)"
      service: s-non-active
  services:
    s-active:
      weighted:
        services:
          - name: s-server1
            weight: 1
          - name: s-server2
            weight: 0
    s-non-active:
      weighted:
        services:
          - name: s-server1
            weight: 0
          - name: s-server2
            weight: 1
    s-server1:
      loadBalancer:
        servers:
          - url: "http://localhost:4000"
    s-server2:
      loadBalancer:
        servers:
          - url: "http://localhost:4001"
